site_name: Minecraft-TeamSpeak Integration
site_description: Documentation for the Minecraft-TeamSpeak Integration Plugin
site_author: Minecraft-TeamSpeak Team
site_url: https://minecraft-teamspeak.github.io/webui/

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home: index.md
  - User Guide: user-guide.md
  - Admin Guide: admin-guide.md
  - About:
    - Changelog: changelog.md
    - Contributing: contributing.md

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true 
