# TeamSpeak Integration Configuration

# TeamSpeak Server Settings
teamspeak:
  host: "localhost"
  port: 10011
  username: "serverquery"
  password: "your_query_password"
  virtual_server_port: 9987  # Port des virtuellen Servers (Standard: 9987)
  update_interval: 30  # seconds

# Database Settings
database:
  type: "sqlite"  # Options: "postgres" or "sqlite"
  # PostgreSQL settings (only used if type is "postgres")
  postgres:
    host: "postgres"
    port: 5432
    database: "minecraft_teamspeak"
    username: "minecraft"
    password: "minecraft"
    pool_size: 10
    connection_timeout: 30000  # milliseconds
  # SQLite settings (only used if type is "sqlite")
  sqlite:
    file: "plugins/TeamSpeakIntegration/database.db"
    pool_size: 5
    connection_timeout: 30000  # milliseconds

# Role Mapping
role_mappings:
  "admin":
    - 1  # Server Group ID for admins
  "moderator":
    - 2  # Server Group ID for moderators
  "vip":
    - 3  # Server Group ID for VIP players

# Cache Settings
cache:
  enabled: true
  max_size: 1000
  expire_after: 3600  # seconds

# Messages
messages:
  prefix: "<dark_gray>[<aqua>TS</aqua>]</dark_gray> "
  already_linked: "<red>Dein Minecraft-Account ist bereits mit TeamSpeak verknüpft!</red>"
  not_linked: "<red>Dein Minecraft-Account ist nicht mit TeamSpeak verknüpft!</red>"
  unlink_success: "<green>Dein Minecraft-Account wurde erfolgreich von TeamSpeak getrennt!</green>"
  link_success: "<green>Dein Minecraft-Account wurde erfolgreich mit TeamSpeak verknüpft!</green>"
  verification_code: "<yellow>Bitte verbinde dich mit TeamSpeak und gib folgenden Code im Chat ein: <green>{code}</green></yellow>"
  teamspeak_not_connected: "<red>Der TeamSpeak-Server ist derzeit nicht verbunden!</red>"
  online_users_header: "<yellow>Online TeamSpeak Benutzer:</yellow>"
  online_user_format: "<gray>• </gray><white>{username}</white>"
