name: Build Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Verhindert parallele Ausführungen und bricht ältere Builds ab
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn clean package -f minecraft-plugin/pom.xml
    
    - name: Upload JAR file
      uses: actions/upload-artifact@v3
      with:
        name: teamspeak-integration
        path: minecraft-plugin/target/teamspeak-integration-*.jar
